receivers:
  otlp:
    protocols:
      grpc:
      http:
  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 5s
          static_configs:
            - targets: ["localhost:8888"]

processors:
  batch:

exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  otlphttp/mimir:
    endpoint: http://mimir:9009/otlp
    compression: none
    tls:
      insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    labels:
      record:
        traceID: traceid
      attributes:
        container.name: "container_name"
        k8s.cluster.name: "k8s_cluster_name"
        severity: "severity"
      resource:
        resource.name: "resource_name"
        severity: "severity"
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true
  logging:
  prometheus:
    endpoint: "otelcol:9464"
  prometheusremotewrite:
    endpoint: http://mimir:9009/api/v1/push

service:
  pipelines:
    traces:
      receivers: [jaeger,otlp]
      processors: [batch]
      exporters: [logging, otlp/tempo]
    metrics:
      receivers: [prometheus,otlp]
      processors: [batch]
      exporters: [logging, prometheusremotewrite, otlphttp/mimir]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, loki]
